# Use an existing Docker image as a base
FROM node:alpine
WORKDIR ./app

# Download and install a dependency
COPY ./package.json .
RUN npm install

# Obtain remaining files from image
COPY ./ ./

# Tell image what to do on container start
CMD ["npm", "run", "start"]